version: "3.9"

services:
  db:
    build: ./db
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: myapp
    environment:
      dbhost: mydb
      apphost: app
      user: root
      password: password
      database: retaildatabase
      port: 3306
    # volumes:
    #   - ./app/src:/app/src
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - "db"
    # command: sh -c "sleep 10s ; /bin/bash"
    # command: tail -f /dev/null
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mypma
    links:
      - db
    restart: always
    ports:
      - 8081:80
