apiVersion: v1
kind: Service
metadata:
  name: retail-db
spec:
  selector:
    app: retail-db
  type: ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-db
  template:
    metadata:
      labels:
        app: retail-db
    spec:
      containers:
        - name: retail-db-container
          image: eddie0228/retail-db:latest
          ports:
            - containerPort: 3306
          # resources:
          #   limits:
          #     memory: "528Mi"
          #     cpu: "1500m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          # resources:
          #   limits:
          #     memory: "528Mi"
          #     cpu: "1500m"
